name: Verify Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    strategy:
        matrix:
            gradle-version: [ '6.0.1', '6.9.2', '7.0.2', '7.4.1' ]
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_SOLUTIONS_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_SOLUTIONS_CACHE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup git user
      # Needed for functional tests executing git commands
        run: |
          git config --global user.name "bot-githubaction"
          git config --global user.email "bot-githubaction@gradle.com"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build -x signArchives -i -PtestGradleVersion=${{ matrix.gradle-version }}
